from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from app.domain.funpay import FunPayEvent, FunPayHealth, MessageReceipt
from app.domain.models import LotOperationResult, RawEmail
from app.domain.notifications import OwnerNotification
from app.domain.pixelstorm import (
    PixelStormAuthenticationState,
    PixelStormAuthResult,
    PixelStormCredentialResult,
    PixelStormHealth,
    PixelStormPasswordChangeResult,
    PixelStormRevocationResult,
    PixelStormSecurityCapabilities,
    PixelStormSessionState,
)


class FunPayPort(Protocol):
    def poll_events(self, *, after: datetime) -> Sequence[FunPayEvent]: ...
    def get_order(self, funpay_order_id: str) -> FunPayEvent | None: ...
    def send_message(
        self, buyer_id: str, text: str, *, idempotency_key: str, now: datetime
    ) -> MessageReceipt: ...
    def get_message_receipt(self, idempotency_key: str) -> MessageReceipt | None: ...
    def get_lot_state(self, external_lot_id: str) -> bool | None: ...
    def verify_lots_disabled(self, external_lot_ids: Sequence[str]) -> LotOperationResult: ...
    def verify_lots_enabled(self, external_lot_ids: Sequence[str]) -> LotOperationResult: ...
    def health(self) -> FunPayHealth: ...
    def disable_lots(self, account_id: str, external_lot_ids: Sequence[str]) -> LotOperationResult: ...
    def enable_lots(self, account_id: str, external_lot_ids: Sequence[str]) -> LotOperationResult: ...


class FunPayTransport(Protocol):
    """Session-consuming transport boundary; no real HTTP implementation exists in PHASE 3."""

    def health(self, session: str) -> FunPayHealth: ...
    def poll_events(self, session: str, *, after: datetime) -> Sequence[FunPayEvent]: ...
    def get_order(self, session: str, funpay_order_id: str) -> FunPayEvent | None: ...
    def send_message(self, session: str, buyer_id: str, text: str, *, idempotency_key: str, now: datetime) -> MessageReceipt: ...
    def get_message_receipt(self, session: str, idempotency_key: str) -> MessageReceipt | None: ...
    def get_lot_state(self, session: str, external_lot_id: str) -> bool | None: ...
    def verify_lots_disabled(self, session: str, external_lot_ids: Sequence[str]) -> LotOperationResult: ...
    def verify_lots_enabled(self, session: str, external_lot_ids: Sequence[str]) -> LotOperationResult: ...
    def disable_lots(self, session: str, account_id: str, external_lot_ids: Sequence[str]) -> LotOperationResult: ...
    def enable_lots(self, session: str, account_id: str, external_lot_ids: Sequence[str]) -> LotOperationResult: ...


class GaijinPort(Protocol):
    def revoke_sessions(self, account_id: str) -> bool: ...
    def rotate_password(self, account_id: str) -> bool: ...
    def verify_access(self, account_id: str) -> bool: ...


class PixelStormAccountPort(Protocol):
    """Production account boundary.  It never falls back to global Gaijin."""

    def health(self, account_id: str) -> PixelStormHealth: ...
    def inspect_authentication_state(self, account_id: str) -> PixelStormAuthenticationState: ...
    def inspect_security_capabilities(self, account_id: str) -> PixelStormSecurityCapabilities: ...
    def inspect_session_state(self, account_id: str) -> PixelStormSessionState: ...
    def authenticate(self, account_id: str, login: str, password: str, *, otp: str | None = None) -> PixelStormAuthResult: ...
    def verify_credentials(self, account_id: str, login: str, password: str) -> PixelStormCredentialResult: ...


class PixelStormSecurityPort(PixelStormAccountPort, Protocol):
    def revoke_sessions(self, account_id: str) -> PixelStormRevocationResult: ...
    def verify_revocation(self, account_id: str) -> PixelStormRevocationResult: ...
    def change_password(self, account_id: str, login: str, current_password: str, pending_password: str) -> PixelStormPasswordChangeResult: ...
    def request_password_change(self, account_id: str, login: str, current_password: str) -> PixelStormPasswordChangeResult: ...
    def complete_password_change(self, account_id: str, reset_url: str, pending_password: str) -> PixelStormPasswordChangeResult: ...


class SecureStorePort(Protocol):
    def set_pending(self, account_id: str, value: str) -> None: ...
    def promote_pending(self, account_id: str) -> None: ...
    def has_pending(self, account_id: str) -> bool: ...
    def get_current_credentials(self, account_id: str) -> tuple[str, str] | None: ...
    def get_pending_credentials(self, account_id: str) -> tuple[str, str] | None: ...
    def set_pending_credentials(self, account_id: str, login: str, password: str) -> None: ...
    def promote_pending_credentials(self, account_id: str) -> None: ...


class OAuthTokenStore(Protocol):
    def get_gmail_refresh_token(self) -> str | None: ...
    def set_gmail_refresh_token(self, token: str) -> None: ...


class WebSessionStore(Protocol):
    def get_funpay_session(self, account_id: str) -> str | None: ...
    def set_funpay_session(self, account_id: str, value: str) -> None: ...
    def clear_funpay_session(self, account_id: str) -> None: ...
    def get_pixelstorm_session(self, account_id: str) -> str | None: ...
    def set_pixelstorm_session(self, account_id: str, value: str) -> None: ...
    def clear_pixelstorm_session(self, account_id: str) -> None: ...


class OwnerNotifier(Protocol):
    def notify(self, notification: OwnerNotification) -> None: ...


class GmailPort(Protocol):
    def get_new_messages(self, *, after: datetime) -> Sequence[RawEmail]: ...


class EphemeralEmailSecretStore(Protocol):
    def put(self, event_id: str, payload: str, *, expires_at: datetime) -> bool: ...
    def consume_once(self, event_id: str, *, claim_token: str, now: datetime) -> str | None: ...
    def discard(self, event_id: str) -> None: ...
    def purge_expired(self, now: datetime) -> int: ...
