from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from app.domain.models import LotOperationResult, RawEmail


class FunPayPort(Protocol):
    def disable_lots(self, account_id: str) -> LotOperationResult: ...
    def send_credentials(self, rental_id: str, *, idempotency_key: str) -> bool: ...
    def enable_lots(self, account_id: str) -> LotOperationResult: ...


class GaijinPort(Protocol):
    def revoke_sessions(self, account_id: str) -> bool: ...
    def rotate_password(self, account_id: str) -> bool: ...
    def verify_access(self, account_id: str) -> bool: ...


class SecureStorePort(Protocol):
    def set_pending(self, account_id: str, value: str) -> None: ...
    def promote_pending(self, account_id: str) -> None: ...
    def has_pending(self, account_id: str) -> bool: ...


class OAuthTokenStore(Protocol):
    def get_gmail_refresh_token(self) -> str | None: ...
    def set_gmail_refresh_token(self, token: str) -> None: ...


class GmailPort(Protocol):
    def get_new_messages(self, *, after: datetime) -> Sequence[RawEmail]: ...


class EphemeralEmailSecretStore(Protocol):
    def put(self, event_id: str, payload: str, *, expires_at: datetime) -> bool: ...
    def consume_once(self, event_id: str, *, claim_token: str, now: datetime) -> str | None: ...
    def discard(self, event_id: str) -> None: ...
    def purge_expired(self, now: datetime) -> int: ...
