from enum import StrEnum


class AccountStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    ACTIVE = "ACTIVE"
    EXPIRING = "EXPIRING"
    REVOKING = "REVOKING"
    ROTATING_PASSWORD = "ROTATING_PASSWORD"
    AVAILABLE_OFFLINE = "AVAILABLE_OFFLINE"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    SECURITY_ALERT = "SECURITY_ALERT"
    DISABLED = "DISABLED"


class RentalStatus(StrEnum):
    RESERVED = "RESERVED"
    ACTIVE = "ACTIVE"
    EXPIRING = "EXPIRING"
    REVOKING = "REVOKING"
    PASSWORD_ROTATION = "PASSWORD_ROTATION"
    FINISHED = "FINISHED"
    CANCELLED = "CANCELLED"
    SECURITY_TERMINATED = "SECURITY_TERMINATED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class FulfillmentStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVATED = "ACTIVATED"
    FULFILLMENT_BLOCKED = "FULFILLMENT_BLOCKED"


class OperationKind(StrEnum):
    DISABLE_LOTS = "DISABLE_LOTS"
    SEND_CREDENTIALS = "SEND_CREDENTIALS"
    REVOKE_SESSIONS = "REVOKE_SESSIONS"
    ROTATE_PASSWORD = "ROTATE_PASSWORD"
    ENABLE_LOTS = "ENABLE_LOTS"


class OperationStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class EmailMessageType(StrEnum):
    LOGIN_OTP = "LOGIN_OTP"
    PASSWORD_CHANGE = "PASSWORD_CHANGE"
    EMAIL_CHANGE = "EMAIL_CHANGE"
    TWO_FACTOR_CHANGE = "2FA_CHANGE"
    SECURITY_CHANGE = "SECURITY_CHANGE"
    UNKNOWN = "UNKNOWN"


class EmailPayloadState(StrEnum):
    AVAILABLE = "AVAILABLE"
    CONSUMED = "CONSUMED"
    UNUSABLE_EXPIRED = "UNUSABLE_EXPIRED"
